---
- name: Provision EC2 Box  
  ec2:
    key_name: "{{ ec2_keypair }}"
    group_id: "{{ ec2_security_group }}"
    instance_type: "{{ ec2_instance_type }}"
    image: "{{ ec2_image }}"
    region: "{{ ec2_region }}"
    instance_tags: '{"Name":"{{ec2_tag_Name}}","Type":"{{ec2_tag_Type}}","Environment":"{{ec2_tag_Environment}}"}'
    wait: true
    count: "{{ ec2_instance_count }}"
    volumes:
      - device_name: /dev/sda1
        device_type: "{{ ec2_device_type }}"
        volume_size: "{{ ec2_volume_size }}"
        delete_on_termination: true
  register: ec2
#- debug: var=item
#  with_items: ec2.instances
# add newly created host to sftpservers group
- add_host: hostname={{ item.public_ip }} groups=sftpservers
  with_items: ec2.instances

- name: Add the newly created EC2 instances) to the local host group (located inside the directory)
  local_action: lineinfile dest=development regexp={{ item.public_ip }} insertafter=[sftpservers] line="{{ item.public_ip }}"
  with_items: ec2.instances

- name: Wait for" "the instances" to boot by checking the ssh port
  wait_for: host={{item.public_ip}} port=22 delay=60 timeout=320 state=started
  with_items: ec2.instances