vsftpd_package: "vsftpd"
vsftpd_config_template_path: /etc/vsftpd.conf
vsftpd_service_enabled: yes
vsftpd_service_state: started
vsftpd_users:
  - username: ftpuser
    name: FTP User
  - username: niteshch
    name: Nitesh Chauhan
  - username: johndoe
    name: John Doe
vsftpd_group: ftp
# default ssl key
vsftpd_key_file: ssl-cert-snakeoil.key
# default ssl cert
vsftpd_cert_file: ssl-cert-snakeoil.pem
# config variables
vsftpd_config: {}
# config template to install, relative to the ansible repository root
vsftpd_config_template:
# optional SELinux booleans to be set i.e. for RedHat
vsftpd_seboolean: {}